apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysdig-shield-dev
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: sysdig-deployments
    notifications.argoproj.io/subscribe.on-sync-failed.slack: sysdig-alerts
    notifications.argoproj.io/subscribe.on-health-degraded.slack: sysdig-alerts
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
  - repoURL: https://charts.sysdig.com
    chart: shield
    targetRevision: "1.28.0"
    helm:
      valueFiles:
      - $values/helm-values/base-values.yaml
      - $values/helm-values/dev-values.yaml
  - repoURL: <YOUR_REPO_URL>
    targetRevision: HEAD
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: sysdig-shield

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
